dist: trusty

language: cpp

sudo: true

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

branches:
  only:
    - master
    - travis

before_script:
  - ./ci/setup.sh

script:
  - ./ci/build.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - attr
      - clang
      - fuse
      - libfuse-dev
      - gettext
      - cmake3
